[
    {
        "Id": "sha256:94e814e2efa8845d95b2112d54497fbad173e45121ce9255b93401392f538499",
        "RepoTags": [
            "ubuntu:latest"
        ],
        "RepoDigests": [
            "ubuntu@sha256:017eef0b616011647b269b5c65826e2e2ebddbe5d1f8c1e56b3599fb14fabec8"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2019-03-12T00:20:17.419392342Z",
        "Container": "94772adb8869651410d18062838667884a555cf1878d567734e99dc695d6f5bf",
        "ContainerConfig": {
            "Hostname": "94772adb8869",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "CMD [\"/bin/bash\"]"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:881686baf75637792ebd93d88243b6f5bb89833ce325f9e32e2e70208f0efb64",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {}
        },
        "DockerVersion": "18.06.1-ce",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/bin/bash"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:881686baf75637792ebd93d88243b6f5bb89833ce325f9e32e2e70208f0efb64",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 88908191,
        "VirtualSize": 88908191,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/a64fe1b870697933594b30ee5bbf3d0b718f5933f0288fe017405b7ba311c7c8/diff:/var/lib/docker/overlay2/62dc4d1a127015305be95a475d7d00679223bbcb10bb416cdadfb32cbf991222/diff:/var/lib/docker/overlay2/e51cd656043d493ef4a1667288dd269a18068f8704ec1241359963e268071526/diff",
                "MergedDir": "/var/lib/docker/overlay2/ffa3fa0c28687446b112757a064d6c46ed0b52d6057f8d99e9f928c95bda8bc3/merged",
                "UpperDir": "/var/lib/docker/overlay2/ffa3fa0c28687446b112757a064d6c46ed0b52d6057f8d99e9f928c95bda8bc3/diff",
                "WorkDir": "/var/lib/docker/overlay2/ffa3fa0c28687446b112757a064d6c46ed0b52d6057f8d99e9f928c95bda8bc3/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:762d8e1a60542b83df67c13ec0d75517e5104dee84d8aa7fe5401113f89854d9",
                "sha256:e45cfbc98a505924878945fdb23138b8be5d2fbe8836c6a5ab1ac31afd28aa69",
                "sha256:d60e01b37e74f12aa90456c74e161f3a3e7c690b056c2974407c9e1f4c51d25b",
                "sha256:b57c79f4a9f3f7e87b38c17ab61a55428d3391e417acaa5f2f761c0e7e3af409"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]
